[multipage-level=1]
= Termux for developers (we! 😎)
include::header.adoc[]

== Creating and using a desktop development environment (with Docker)

=== Prerequisites

. A Bash shell running on macOS, Linux or Windows (with Cygwin
installed).
. Docker installed. (of course! 😄)

[WARNING]
====
Until now, *[red]#the steps below were tested only in macOS and
Ubuntu Linux operating systems#*.
Here are the details:

macOS: ::
----
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.6
BuildVersion:   19G2021

$ docker --version
Docker version 19.03.12, build 48a66213fe
----

Ubuntu: ::
----
$ cat  /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

$ docker --version
Docker version 19.03.12, build 48a66213fe
----
====

=== Clone paulojeronimo/termux-docker

Here I present you a nice and productive way to create your
applications before package than and liberate their use.

----
$ mkdir ~/lab-termux && cd $_
$ git clone https://github.com/paulojeronimo/termux-docker && cd `basename $_`
----

NOTE: You can also fork this repo and use your own! 😃 +
You will see that my repo is a fork too (with some improvements) from
https://github.com/xeffyr/termux-docker[xeffyr/termux-docker^]!

=== Build and run your own Docker image

Copy `config.sample.sh` to `config.sh` and configure your {DockerHub}
username on it.

----
$ cp config.sample.sh config.sh
$ sed -i 's/xeffyr/paulojeronimo/g' config.sh
----

[NOTE]
====
. If you are using macOS, change the last command to `gsed`.
. Change `paulojeronimo` to your username on {DockerHub}.
====

Invoke `build-all.sh` script:

----
$ ./build-all.sh
----

Test a docker container creation by invoking the `run.sh` script:

----
$ ./run.sh
----

Type kbd:[Ctrl+D] to exit.

NOTE: Note (by typing a `docker ps -a`) that a container
named `termux-docker-i686-XXXXXXX` will remain running.

== Test your Docker image to build this site

=== Clone paulojeronimo/termux-presentation

----
$ cd ~/lab-termux
$ git clone https://github.com/paulojeronimo/termux-presentation && cd `basename $_`
----

=== Copy the run.sh and config.sh (from termux-docker)

----
$ cp ../termux-docker/run.sh ./termux-docker.sh
$ cp ../termux-docker/config.sh .
----

=== Build this site by creating a termux-docker container

----
$ ./termux-docker.sh
----

Sample output for the command above:

----
include::termux-docker.txt[]
----

Call `build.sh` inside the shell provided by the container:

----
$ ./build.sh
Building content in termux environment ...
Skipping the call to "build-multipage-version" for termux environment!
Reason: termux can not run Docker (Yet! Maybe someday!?)
Follow this link:
https://www.reddit.com/r/termux/comments/av6z2s/how_to_install_docker_on_termux/ehd5yus/
Generated content (the "build" directory tree shown below):
build
└── singlepage
    ├── asciidoctor.css
    └── index.html

1 directory, 2 files
----

WARNING: In the first execution of the command above, the `build.sh`
script will install the required packages. So, the output will be more
extensive than showed.
